---
#             B7 practice work, 
#             Y.Zuzia, august 31, 2022
#   install PostGreSQL on vm - ubuntu

- name:       Install and run PostGreSQL server
  hosts:            vm
  gather_facts:     yes
  become:           yes

  tasks:

   - name:          0. Set up prerequisites
     apt:
       pkg:
       - gnupg
       - python3-psycopg2
       - acl
       update_cache: yes

   - name:     1. Import the repository signing key
     apt_key:
       url:      https://www.postgresql.org/media/keys/ACCC4CF8.asc
       state:    present

   - name:     2. Set up PostGreSQL repository
     apt_repository:
       repo:     deb http://apt.postgresql.org/pub/repos/apt "{{ ansible_distribution_release}}-pgdg" main
       state:    present
       filename: pgdg.list

   - name:     3. Install requied version of PostgreSQL
     apt:
       name:   "postgresql-{{ postgresql_ver }}"
       update_cache:   yes
       state:  present

   - include:   sensitive.yml

   - name:     4.1. Create new DataBase in PostGreSQL
     become:  yes
     become_user: postgres
     community.postgresql.postgresql_db:
       name:   user1db

   - name:     4.2.0. Create unix user
     user:
       name:    user1
       comment: for peer auth to postgres
       password:  "{{ user1_password }}"
       # password must be encripted
       
   - name:     4.2. Create new db user
     become:  yes
     become_user: postgres
     community.postgresql.postgresql_user:
       db:    user1db
       name:  user1
       password: "{{ user1_password }}"

   - name: 4.3. Grant privelegies to db
     become:    yes
     become_user:  postgres
     community.postgresql.postgresql_privs:
       database:  user1db
       privs:    ALL
       type:     database
       roles:    user1  
