---
 - name:      Loop test playbook
   hosts:     all
#   become:    yes


   tasks:
   - name:    Say Hello in loop
     debug:   msg="Hello to {{ item }}"
     loop:
       - "Vasia"
       - "Petya"
       - "Prohor"
#       - "Masha"
#       - "Olya"
   - name:         use Until loop
     shell:     echo -n Z >> myfile.txt && cat myfile.txt
     register:  result
     delay:     1
     retries:   10
     until: result.stdout.find("ZZZZ") == false
   
   - debug:
        var:     result.stdout     
        
