---
# tasks file for nginx-php-fpm
- name:  0.1 Prerequisite - packets
  apt:
    pkg:
    - curl
    - gnupg2
    - ca-certificates
    - lsb-release
    update_cache:   yes

- name:  0.2 Prerequisite - install nginx signing key
  apt_key:
    url:   https://nginx.org/keys/nginx_signing.key
    state: present

- name:  0.2 Prerequisite - update repo for nginx
  apt_repository:
    repo: "{{ item }}"      
    state:     present
    filename:  nginx
  loop:
     - deb http://nginx.org/packages/ubuntu {{ ansible_lsb.codename }} nginx
     - deb-src https://nginx.org/packages/mainline/ubuntu/ {{ ansible_lsb.codename }} nginx

- name:        1. install nginx + php-fpm
  apt:
     name: 
       - nginx
       - php-fpm
     state: present
     update_cache: yes

- name:    2.1 Configuring nginx for work with php-fpm
  copy:
    src:  nginx-fpm.conf
    dest: /etc/nginx/conf.d/
  notify:  restart nginx

- name:    2.2 Copy start page for nginx
  copy:
    src:   index.php
    dest:  /usr/share/nginx/html/ 
  notify:   restart nginx 

