---
#             B6 practice work, HW-03
#             Y.Zuzia, july 31, 2022
#   install Docker on app group: vm2  - ubuntu, vm3 - CentOs8

- name:       Install and run Docker
  hosts:            app
  gather_facts:     yes
  become:           yes

  tasks:
   - name:          1.1 Set up the repository for ubuntu
     apt:
       pkg:
       - ca-certificates
       - curl
       - gnupg
       - lsb-release
       update_cache: yes
     when: ansible_os_family=="Debian"

   - name:          1.2 Set up prerequisites for CentOs8
     dnf:   
        name:
        - gnome-terminal
        - dnf-plugins-core
        state: latest
     when: ansible_os_family=="RedHat"


   - name:         2.1  Create keyring directory   Add Docker’s official GPG key (need to dearmor)
     file:
        path:     /etc/apt/keyrings
        state:    directory
     when: ansible_os_family=="Debian"

   - name:         2.2Copy GPG key
     uri:
        url:     https://download.docker.com/linux/ubuntu/gpg
        dest:    /etc/apt/keyrings
        mode:    0755
     when: ansible_os_family=="Debian"

   - name:         2. Dearmor key
     command:     
        cmd:      gpg -o /etc/apt/keyrings/docker.gpg --dearmor /etc/apt/keyrings/gpg
     when: ansible_os_family=="Debian"

      
   - name:        3.1 Add  docker source to the repository, for ubuntu
     apt_repository:
       repo:         deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable
       state:        present
       filename:     docker
     when: ansible_os_family=="Debian"

   - name:        3.2 Add  docker source to the repository, for CentOs8
     command:
       cmd:   dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
     when: ansible_os_family=="RedHat"    

   - name:       4.1 Apt Update and Install Docker for ubuntu
     apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
        update_cache:     yes
     when: ansible_os_family=="Debian"

   - name:       4.2 dnf update and Install Docker for CentOs8
     dnf:
       name:
       - docker-ce
       - docker-ce-cli
       - containerd.io
       - docker-compose-plugin
       state: latest
     when: ansible_os_family=="RedHat"
