---
#             B6 practice work, HW-03
#             Y.Zuzia, july 31, 2022
#   install PostGreSQL on database group: vm1  - ubuntu

- name:       Install and run PostGreSQL server
  hosts:            database
  gather_facts:     yes
  become:           yes

  tasks:

   - name:          0. Set up prerequisites
     apt:
       pkg:
       - gnupg
       - python3-psycopg2
       - acl
       update_cache: yes

   - name:     1. Import the repository signing key
     apt_key:
       url:      https://www.postgresql.org/media/keys/ACCC4CF8.asc
       state:    present

   - name:     2. Set up PostGreSQL repository
     apt_repository:
       repo:     deb http://apt.postgresql.org/pub/repos/apt "{{ ansible_distribution_release}}-pgdg" main
       state:    present
       filename: pgdg.list

   - name:     3. Install requied version of PostgreSQL
     apt:
       name:   "postgresql-{{ postgresql_ver }}"
       update_cache:   yes
       state:  present

   - name:    4. Create database directory.
     file:
       path:   "{{ postgresql_data }}"
       state:  directory
       mode:   0766
   
   - name:     5.  Configure PostGreSQL server - setup database directory.
     template:
       src:    ./postgresql.conf
       dest:   "/etc/postgresql/{{ postgresql_ver}}/main"
     notify:
     - restart_postgresql  

  handlers:
  - name: restart_postgresql
    service: name=postgresql state=restarted
    
# Create the file repository configuration:
#sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

# Import the repository signing key:
#wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

# Update the package lists:
#sudo apt-get update

# Install the latest version of PostgreSQL.
# If you want a specific version, use 'postgresql-12' or similar instead of 'postgresql':
# sudo apt-get -y install postgresql 